When I write docker-compose up, this happens:

kusos@dan-lt:~/pyproj$ docker-compose up
[+] Running 3/3
 ✔ Network pyproj_postgres  Created                                                                                                                                  0.0s 
 ✔ Container pyproj-db-1    Created                                                                                                                                  0.1s 
 ✔ Container pyproj-app-1   Created                                                                                                                                  0.1s 
Attaching to pyproj-app-1, pyproj-db-1
pyproj-db-1   | The files belonging to this database system will be owned by user "postgres".
pyproj-db-1   | This user must also own the server process.
pyproj-db-1   | 
pyproj-db-1   | The database cluster will be initialized with locale "en_US.utf8".
pyproj-db-1   | The default database encoding has accordingly been set to "UTF8".
pyproj-db-1   | The default text search configuration will be set to "english".
pyproj-db-1   | 
pyproj-db-1   | Data page checksums are disabled.
pyproj-db-1   | 
pyproj-db-1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
pyproj-db-1   | creating subdirectories ... ok
pyproj-db-1   | selecting dynamic shared memory implementation ... posix
pyproj-db-1   | selecting default max_connections ... 100
pyproj-db-1   | selecting default shared_buffers ... 128MB
pyproj-db-1   | selecting default time zone ... Etc/UTC
pyproj-db-1   | creating configuration files ... ok
pyproj-db-1   | running bootstrap script ... ok
pyproj-app-1  | Traceback (most recent call last):
pyproj-app-1  |   File "/code/app.py", line 14, in <module>
pyproj-app-1  |     conn = psycopg2.connect(db_string)
pyproj-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyproj-app-1  |   File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
pyproj-app-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
pyproj-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyproj-app-1  | psycopg2.OperationalError: connection to server at "db" (172.29.0.2), port 5432 failed: Connection refused
pyproj-app-1  |         Is the server running on that host and accepting TCP/IP connections?
pyproj-app-1  | 
pyproj-db-1   | performing post-bootstrap initialization ... ok
pyproj-app-1 exited with code 1
pyproj-db-1   | initdb: warning: enabling "trust" authentication for local connections
pyproj-db-1   | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
pyproj-db-1   | syncing data to disk ... ok
pyproj-db-1   | 
pyproj-db-1   | 
pyproj-db-1   | Success. You can now start the database server using:
pyproj-db-1   | 
pyproj-db-1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
pyproj-db-1   | 
pyproj-db-1   | waiting for server to start....2023-05-26 03:34:55.830 UTC [48] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pyproj-db-1   | 2023-05-26 03:34:55.834 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pyproj-db-1   | 2023-05-26 03:34:55.842 UTC [51] LOG:  database system was shut down at 2023-05-26 03:34:55 UTC
pyproj-db-1   | 2023-05-26 03:34:55.848 UTC [48] LOG:  database system is ready to accept connections
pyproj-db-1   |  done
pyproj-db-1   | server started
pyproj-db-1   | CREATE DATABASE
pyproj-db-1   | 
pyproj-db-1   | 
pyproj-db-1   | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_fixtures.sql
pyproj-db-1   | CREATE TABLE
pyproj-db-1   | 
pyproj-db-1   | 
pyproj-db-1   | waiting for server to shut down...2023-05-26 03:34:56.085 UTC [48] LOG:  received fast shutdown request
pyproj-db-1   | .2023-05-26 03:34:56.089 UTC [48] LOG:  aborting any active transactions
pyproj-db-1   | 2023-05-26 03:34:56.091 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
pyproj-db-1   | 2023-05-26 03:34:56.091 UTC [49] LOG:  shutting down
pyproj-db-1   | 2023-05-26 03:34:56.095 UTC [49] LOG:  checkpoint starting: shutdown immediate
pyproj-db-1   | 2023-05-26 03:34:56.187 UTC [49] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.028 s, sync=0.056 s, total=0.097 s; sync files=250, longest=0.005 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
pyproj-db-1   | 2023-05-26 03:34:56.193 UTC [48] LOG:  database system is shut down
pyproj-db-1   |  done
pyproj-db-1   | server stopped
pyproj-db-1   | 
pyproj-db-1   | PostgreSQL init process complete; ready for start up.
pyproj-db-1   | 
pyproj-db-1   | 2023-05-26 03:34:56.310 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pyproj-db-1   | 2023-05-26 03:34:56.310 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pyproj-db-1   | 2023-05-26 03:34:56.311 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pyproj-db-1   | 2023-05-26 03:34:56.319 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pyproj-db-1   | 2023-05-26 03:34:56.327 UTC [66] LOG:  database system was shut down at 2023-05-26 03:34:56 UTC
pyproj-db-1   | 2023-05-26 03:34:56.334 UTC [1] LOG:  database system is ready to accept connections
pyproj-db-1   | 2023-05-26 03:35:38.776 UTC [1] LOG:  received fast shutdown request
pyproj-db-1   | 2023-05-26 03:35:38.780 UTC [1] LOG:  aborting any active transactions
pyproj-db-1   | 2023-05-26 03:35:38.788 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
pyproj-db-1   | 2023-05-26 03:35:38.790 UTC [64] LOG:  shutting down
pyproj-db-1   | 2023-05-26 03:35:38.793 UTC [64] LOG:  checkpoint starting: shutdown immediate
pyproj-db-1   | 2023-05-26 03:35:38.818 UTC [64] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.009 s, total=0.028 s; sync files=13, longest=0.005 s, average=0.001 s; distance=229 kB, estimate=229 kB
pyproj-db-1   | 2023-05-26 03:35:38.823 UTC [1] LOG:  database system is shut down
pyproj-db-1 exited with code 0